### ISSUE TITLE
Add UTF-8 support

### ISSUE THREAD

**Issue by katarn88** [gajosadrian/Gajos-Framework#1]
In config.lua, this should be changed in-case EngiN33R's utf-8 library is being used (which SQ has said could possibly become included in CS2D). This will future proof the code.
```Lua
COLOR = {}
for _, v in pairs(COLOR_VALUE) do
    COLOR[_] = '\169' .. v
end
```
To:
```Lua
COLOR = {}
local code = string.char(0xA9)

if utf8 then
    -- utf8 encoding of the copyright symbol
    code = string.char(0xC2)..string.char(0xA9)
end

for _, v in pairs(COLOR_VALUE) do
    COLOR[_] = code .. v
end
```

Without that, if the utf8 library is being used, any string sent to `msg`, `msg2` or `print` that contains the character 0xA9 (©) will raise an error.

You will want to use `code` anywhere you would normally use \169, 0xA9, or ©

You could add a function to get the correct color code symbol anywhere else
```Lua
-- must be below   ... local code = ...   from above
function C(r,g,b)
    -- update: return color code when no args are passed
    if not r then
        return code
    end
    g = g or 0
    b = b or 0
    return string.format("%s%0.3u%0.3u%0.3u", code, r, g, b)
end
-- used like:    msg(C(255) .. "This message is red!")
```

Update: fixed the `C` function.

**Comment by gajosadrian** [comment]
solved ;) 
thx!

**Comment by gajosadrian** [comment]
thx!
